name: 'Checkov Scan Composite Action'
description: 'Run Checkov security scan on Terraform code'
runs:
  using: 'composite'
  steps:
    - name: Run Checkov (IaC security scan)
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ inputs.checkov-path }}
        framework: terraform
        output_format: cli,sarif
        output_file_path: console,${{ inputs.checkov-path }}/results.sarif

    - name: Upload Checkov Results
      uses: actions/upload-artifact@v4
      with:
        name: results.sarif
        path: ${{ inputs.checkov-path }}/results.sarif
inputs:
  checkov-path:
    description: 'Directory for Checkov scan'
    required: true
