name: Multi-Stage Example

on:
  workflow_dispatch:
    inputs:
      always-run:
        description: 'If true, jobs will always set their output to 1.'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - '**'


jobs:
  pair1:
    uses: ./.github/workflows/plan-apply-pair.yml
    with:
      always-run: ${{ github.event.inputs.always-run }}
  pair2:
    needs: pair1
    if: always()
    uses: ./.github/workflows/plan-apply-pair.yml
    with:
      always-run: ${{ github.event.inputs.always-run }}
  pair3:
    needs: pair2
    if: always()
    uses: ./.github/workflows/plan-apply-pair.yml
    with:
      always-run: ${{ github.event.inputs.always-run }}
  pair4:
    needs: pair3
    if: always()
    uses: ./.github/workflows/plan-apply-pair.yml
    with:
      always-run: ${{ github.event.inputs.always-run }}
  debug:
    needs: [pair1, pair2, pair3, pair4]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Print all plan-apply pair outputs
        run: |
          echo "pair1 random-exit: ${{ needs.pair1.outputs.random-exit }}"
          echo "pair2 random-exit: ${{ needs.pair2.outputs.random-exit }}"
          echo "pair3 random-exit: ${{ needs.pair3.outputs.random-exit }}"
          echo "pair4 random-exit: ${{ needs.pair4.outputs.random-exit }}"


