name: Multi-Stage Example

on:
  workflow_dispatch:
    inputs:
      always-run:
        description: 'If true, jobs will always set their output to 1.'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - '**'

jobs:
  a1:
    runs-on: ubuntu-latest
    outputs:
      random-exit: ${{ steps.random-step.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run random-exit.sh
        id: random-step
        run: |
          chmod +x ./random-exit.sh
          if [[ "${{ github.event.inputs.always-run }}" == "true" ]]; then
            result=1
          else
            ./random-exit.sh
            result=$?
          fi
          echo "Script exit code: $result"
          echo "result=$result" >> $GITHUB_OUTPUT

  a2:
    needs: a1
    if: needs.a1.outputs.random-exit == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello with Job Name
        run: echo "hello a2"

  b1:
    needs: [a2]
    if: always()
    runs-on: ubuntu-latest
    outputs:
      random-exit: ${{ steps.random-step.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run random-exit.sh
        id: random-step
        run: |
          chmod +x ./random-exit.sh
          if [[ "${{ github.event.inputs.always-run }}" == "true" ]]; then
            result=1
          else
            ./random-exit.sh
            result=$?
          fi
          echo "Script exit code: $result"
          echo "result=$result" >> $GITHUB_OUTPUT

  b2:
    needs: b1
    if: needs.b1.outputs.random-exit == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello with Job Name
        run: echo "hello b2"
