name: Multi-Stage Matrix Example

on:
  workflow_dispatch:
    inputs:
      always-run:
        description: 'If true, jobs will always set their output to 1.'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - '**'

jobs:
  random-exit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair: [a, b, c, d]
    outputs:
      random-exit: ${{ steps.random-step.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run random-exit.sh
        id: random-step
        run: |
          set +e
          chmod +x ./random-exit.sh
          if [[ "${{ github.event.inputs.always-run }}" == "true" ]]; then
            result=1
          else
            ./random-exit.sh
            result=$?
          fi
          echo "Script exit code: $result"
          echo "result=$result" >> $GITHUB_OUTPUT
      - name: Print result
        run: "echo \"${{ matrix.pair }}1 random-exit: ${{ steps.random-step.outputs.result }}\""

  followup:
    needs: random-exit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair: [a, b, c, d]
    if: needs.random-exit.outputs.random-exit == '1'
    steps:
      - name: Print Hello with Job Name
        run: echo "hello ${{ matrix.pair }}2"
      - name: Print previous output
        run: 'echo "${{ matrix.pair }}1 random-exit: ${{ needs.random-exit.outputs.random-exit }}"'
