name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      checkov-path:
        required: true
        type: string
      ARM_CLIENT_ID:
        required: true
        type: string
      ARM_TENANT_ID:
        required: true
        type: string
      ARM_SUBSCRIPTION_ID:
        required: true
        type: string
      runner:
        required: false
        type: string
        default: ubuntu-latest

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true

jobs:
  terraform-plan:
    runs-on: ${{ inputs.runner }}
    outputs:
      tfplanExitCode: ${{ steps.plan.outputs.tfplanExitCode }}
    steps:
      - name: Terraform Plan
        id: plan
        uses: spectrum048k/github-templates/.github/actions/terraform-plan-composite@main
        with:
          working-directory: ${{ inputs.working-directory }}
          ARM_CLIENT_ID: ${{ inputs.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ inputs.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ inputs.ARM_SUBSCRIPTION_ID }}

  checkov-scan:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkov Scan
        uses: spectrum048k/github-templates/.github/actions/checkov-composite@main
        with:
          checkov-path: ${{ inputs.checkov-path }}

  terraform-apply:
    needs: [terraform-plan, checkov-scan]
    runs-on: ${{ inputs.runner }}
    if: needs.terraform-plan.outputs.tfplanExitCode == '2'
    steps:
      - name: Debug plan output
        run: |
          echo "Plan exit code: '${{ needs.terraform-plan.outputs.tfplanExitCode }}'"
      - name: Terraform Apply
        uses: spectrum048k/github-templates/.github/actions/terraform-apply-composite@main
        with:
          working-directory: ${{ inputs.working-directory }}
          ARM_CLIENT_ID: ${{ inputs.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ inputs.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ inputs.ARM_SUBSCRIPTION_ID }}
