name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      checkov-path:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        uses: ../actions/terraform-plan-composite@main
        with:
          working-directory: ${{ inputs.working-directory }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkov Scan
        uses: ../actions/checkov-composite@main
        with:
          checkov-path: ${{ inputs.checkov-path }}

  terraform-apply:
    needs: [terraform-plan, checkov-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        uses: ../actions/terraform-apply-composite@main
        with:
          working-directory: ${{ inputs.working-directory }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
